services:
  - type: web
    name: image-processor
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/static/uploads
    # Thêm các biến môi trường khác vào đây sau khi tạo service trên Render
    # - key: SECRET_KEY
    #   generateValue: true
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: image-processor-db
    #     property: connectionString
